In [161]:
import numpy as np
%load_ext autoreload
%autoreload 2
%precision %i
from visdrone.utils import seqnms, result_utils

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Test 1, consecutive

In [213]:
MAX_BB = 200

In [214]:
proposals = np.asarray([
    [
        [0, 0, 10, 10, 0.3],
        [0, 0, 10, 10, 0.01],
        [0, 0, 10, 10, 0.5],
        [20, 20, 40, 40, 0.01],
    ],
    [
        [0, 0, 10, 10, 0.7],
        [0, 0, 10, 10, 0.1],
        [20, 20, 40, 40, 0.01],
        [0,0,0,0, 0],
    ],
    [
        [0, 0, 10, 10, 0.9],
        [20, 20, 40, 40, 0.15],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
    ]
])
proposals = np.array([np.array(v) for v in proposals])
proposals = np.pad(proposals, [(0, 0), (0, MAX_BB - 4), (0, 0)], mode='constant')
# valid_proposals = [list(range(i)) for i in [4, 3, 2]]
seqnms.find_best_seq(proposals, num_frames=3, rescore='max')

([2, 0, 0], array([[ 0. ,  0. , 10. , 10. ,  0.9],
        [ 0. ,  0. , 10. , 10. ,  0.9],
        [ 0. ,  0. , 10. , 10. ,  0.9]]), 0, 2)

In [189]:
num_bb_perF = [4, 3, 2]
ret = seqnms.seq_nms_core(proposals, len(proposals), num_bb_perF)
print(len(ret))
for i, v in enumerate(ret):
    print(' frame ', i)
    print(v)

3
 frame  0
[[ 0.          0.         10.         10.          0.7       ]
 [20.         20.         40.         40.          0.05666667]]
 frame  1
[[ 0.          0.         10.         10.          0.7       ]
 [20.         20.         40.         40.          0.05666667]]
 frame  2
[[ 0.          0.         10.         10.          0.7       ]
 [20.         20.         40.         40.          0.05666667]]


# Non-consecutive

In [190]:
proposals = np.asarray([
    [
        [0, 0, 10, 10, 0.9],
        [20, 20, 40, 40, 0.15],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
    ],
    [
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
    ],
    [
        [0, 0, 10, 10, 0.3],
        [0, 0, 10, 10, 0.01],
        [0, 0, 10, 10, 0.5],
        [20, 20, 40, 40, 0.01],
    ],
    [
        [0, 0, 10, 10, 0.7],
        [0, 0, 10, 10, 0.1],
        [20, 20, 40, 40, 0.01],
        [0,0,0,0, 0],
    ],
    [
        [0, 0, 10, 10, 0.9],
        [20, 20, 40, 40, 0.15],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
    ],
    [
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
    ],
    [
        [0, 0, 10, 10, 0.7],
        [0, 0, 10, 10, 0.1],
        [20, 20, 40, 40, 0.01],
        [0,0,0,0, 0],
    ],
])
proposals = np.array([np.array(v) for v in proposals])
proposals = np.pad(proposals, [(0, 0), (0, MAX_BB - 4), (0, 0)], mode='constant')
# expect : [2,0,0] [2, 5)
seqnms.find_best_seq(proposals, num_frames=len(proposals))

([2, 0, 0], array([[ 0. ,  0. , 10. , 10. ,  0.7],
        [ 0. ,  0. , 10. , 10. ,  0.7],
        [ 0. ,  0. , 10. , 10. ,  0.7]]), 2, 4)

In [192]:
num_bb_perF = [2, 0, 4, 3, 2, 0, 4]
ret = seqnms.seq_nms_core(proposals, len(proposals), num_bb_perF)
print(len(ret))
for i, v in enumerate(ret):
    print(' frame ', i)
    print(v)

7
 frame  0
[[ 0.    0.   10.   10.    0.9 ]
 [20.   20.   40.   40.    0.15]]
 frame  1
[]
 frame  2
[[ 0.          0.         10.         10.          0.7       ]
 [20.         20.         40.         40.          0.05666667]]
 frame  3
[[ 0.          0.         10.         10.          0.7       ]
 [20.         20.         40.         40.          0.05666667]]
 frame  4
[[ 0.          0.         10.         10.          0.7       ]
 [20.         20.         40.         40.          0.05666667]]
 frame  5
[]
 frame  6
[[0.e+00 0.e+00 1.e+01 1.e+01 7.e-01]
 [2.e+01 2.e+01 4.e+01 4.e+01 1.e-02]]


# Case

In [152]:
proposals = np.asarray([
    [
        [0,0,0,0, 0],
        [20, 20, 40, 40, 0.15],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
    ],
    [
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
    ],
    [
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [20, 20, 40, 40, 0.01],
    ],
    [
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [20, 20, 40, 40, 0.01],
        [0,0,0,0, 0],
    ],
    [
        [0,0,0,0, 0],
        [20, 20, 40, 40, 0.15],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
    ],
    [
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
        [0,0,0,0, 0],
    ],
    [
        [0, 0, 10, 10, 0.07],
        [0, 0, 10, 10, 0.1],
        [20, 20, 40, 40, 0.01],
        [0,0,0,0, 0],
    ],
])
proposals = np.array([np.array(v) for v in proposals])
proposals = np.pad(proposals, [(0, 0), (0, MAX_BB - 4), (0, 0)], mode='constant')
# expect : [2,3,4] [2, 5)
seqnms.find_best_seq(proposals, num_frames=len(proposals))

([3, 2, 1],
 array([[20.        , 20.        , 40.        , 40.        ,  0.05666667],
        [20.        , 20.        , 40.        , 40.        ,  0.05666667],
        [20.        , 20.        , 40.        , 40.        ,  0.05666667]]),
 2,
 4)

# prepare data

In [160]:
indir = ['/tmp/val896_A2enhance', '/tmp/valori_gavidseq/']

In [196]:
r =result_utils.prepare_seqnms_proposals(indir)
clip1 = r['uav0000086_00000_v']
clip1cls1, nbbpF = clip1[0]

In [197]:
clip1cls1.shape

(464, 200, 5)

In [198]:
nbbpF

[101,
 104,
 105,
 104,
 110,
 103,
 107,
 104,
 97,
 100,
 102,
 98,
 106,
 107,
 104,
 100,
 107,
 102,
 101,
 97,
 101,
 108,
 101,
 102,
 106,
 107,
 100,
 105,
 108,
 104,
 106,
 104,
 106,
 105,
 106,
 102,
 106,
 109,
 108,
 120,
 110,
 111,
 115,
 115,
 116,
 113,
 111,
 99,
 108,
 110,
 104,
 108,
 106,
 110,
 115,
 112,
 108,
 103,
 113,
 112,
 111,
 112,
 113,
 113,
 117,
 122,
 112,
 115,
 116,
 116,
 122,
 108,
 107,
 115,
 116,
 109,
 115,
 106,
 107,
 112,
 110,
 114,
 111,
 105,
 105,
 110,
 104,
 103,
 105,
 105,
 115,
 111,
 111,
 110,
 107,
 105,
 108,
 110,
 121,
 104,
 110,
 111,
 109,
 114,
 112,
 117,
 119,
 112,
 117,
 113,
 116,
 114,
 121,
 112,
 116,
 117,
 120,
 121,
 113,
 105,
 112,
 114,
 105,
 120,
 111,
 112,
 118,
 116,
 115,
 115,
 115,
 111,
 117,
 119,
 119,
 124,
 125,
 115,
 116,
 118,
 120,
 115,
 118,
 122,
 122,
 117,
 113,
 120,
 118,
 117,
 122,
 125,
 128,
 114,
 116,
 118,
 112,
 110,
 116,
 125,
 122,
 126,
 124,
 125,
 131,
 133,
 129,
 1

In [217]:
out = seqnms.seq_nms_core(clip1cls1, len(clip1cls1), nbbpF)

58365
57234
56159


KeyboardInterrupt: 